/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUpdateRouteImport } from './routes/admin.update'
import { Route as AdminRevokeRouteImport } from './routes/admin.revoke'
import { Route as AdminManageRouteImport } from './routes/admin.manage'
import { Route as AdminIssueRouteImport } from './routes/admin.issue'
import { Route as AdminCidRouteImport } from './routes/admin.cid'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUpdateRoute = AdminUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevokeRoute = AdminRevokeRouteImport.update({
  id: '/revoke',
  path: '/revoke',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssueRoute = AdminIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCidRoute = AdminCidRouteImport.update({
  id: '/cid',
  path: '/cid',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/share': typeof ShareRoute
  '/admin/cid': typeof AdminCidRoute
  '/admin/issue': typeof AdminIssueRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/revoke': typeof AdminRevokeRoute
  '/admin/update': typeof AdminUpdateRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/share': typeof ShareRoute
  '/admin/cid': typeof AdminCidRoute
  '/admin/issue': typeof AdminIssueRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/revoke': typeof AdminRevokeRoute
  '/admin/update': typeof AdminUpdateRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/share': typeof ShareRoute
  '/admin/cid': typeof AdminCidRoute
  '/admin/issue': typeof AdminIssueRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/revoke': typeof AdminRevokeRoute
  '/admin/update': typeof AdminUpdateRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/credentials'
    | '/share'
    | '/admin/cid'
    | '/admin/issue'
    | '/admin/manage'
    | '/admin/revoke'
    | '/admin/update'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credentials'
    | '/share'
    | '/admin/cid'
    | '/admin/issue'
    | '/admin/manage'
    | '/admin/revoke'
    | '/admin/update'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/credentials'
    | '/share'
    | '/admin/cid'
    | '/admin/issue'
    | '/admin/manage'
    | '/admin/revoke'
    | '/admin/update'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  ShareRoute: typeof ShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/update': {
      id: '/admin/update'
      path: '/update'
      fullPath: '/admin/update'
      preLoaderRoute: typeof AdminUpdateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revoke': {
      id: '/admin/revoke'
      path: '/revoke'
      fullPath: '/admin/revoke'
      preLoaderRoute: typeof AdminRevokeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issue': {
      id: '/admin/issue'
      path: '/issue'
      fullPath: '/admin/issue'
      preLoaderRoute: typeof AdminIssueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cid': {
      id: '/admin/cid'
      path: '/cid'
      fullPath: '/admin/cid'
      preLoaderRoute: typeof AdminCidRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCidRoute: typeof AdminCidRoute
  AdminIssueRoute: typeof AdminIssueRoute
  AdminManageRoute: typeof AdminManageRoute
  AdminRevokeRoute: typeof AdminRevokeRoute
  AdminUpdateRoute: typeof AdminUpdateRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCidRoute: AdminCidRoute,
  AdminIssueRoute: AdminIssueRoute,
  AdminManageRoute: AdminManageRoute,
  AdminRevokeRoute: AdminRevokeRoute,
  AdminUpdateRoute: AdminUpdateRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  ShareRoute: ShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
